taxonomy_menu.taxonomy_menu.*:
  type: config_entity
  label: 'Taxonomy Menu config'
  mapping:
    id:
      type: string
      label: 'ID'
    label:
      type: label
      label: 'Label'
    vocabulary:
      type: string
      label: 'Vocabulary'
    starting_term:
      type: integer
      label: 'Starting Term'
    menu:
      type: string
      label: 'Menu'
    expanded:
      type: boolean
      label: 'Expanded'
    depth:
      type: integer
      label: 'Depth'
    menu_parent:
      type: string
      label: 'Menu parent'
    description_field_name:
      type: string
      label: 'Description field name'
    use_term_weight_order:
      type: boolean
      label: 'Use term weight order'
